/* eslint-disable no-unused-vars */
/* eslint-disable no-shadow */

export enum ActionButtonType {
  MANAGEMENT_ADD = 'MANAGEMENT_ADD',
  MANAGEMENT_EDIT = 'MANAGEMENT_EDIT',
  PRODUCTS_ADD = 'PRODUCTS_ADD',
  PRODUCTS_EDIT = 'PRODUCTS_EDIT',
  PRODUCTS_DELETE = 'PRODUCTS_DELETE',
  PRODUCTS_DETAILS = 'PRODUCTS_DETAILS',
  ORDERS_DELETE = 'ORDERS_DELETE',
  ORDERS_CHANGE_TO_PAID = 'ORDERS_CHANGE_TO_PAID',
  ORDER_CHANGE_STATUS = 'ORDER_CHANGE_STATUS',
  STAFF_ADD = 'STAFF_ADD',
  STAFF_DELETE = 'STAFF_DELETE',
  STAFF_CHANGE = 'STAFF_CHANGE',
  EXPORT_ORDERS = 'EXPORT_ORDERS',
}
