/* eslint-disable no-unused-vars */
/* eslint-disable no-shadow */

export enum Colors {
  PRIMARY_RED = 'primary-red',
  PRIMARY_BLACK = 'primary-black',
  PRIMARY_RED_OPACITY = 'primary-red-opacity',
  GREEN = 'green',
  GUN_POWDER = 'gun-powder',
  GUN_POWDER_LIGHT = 'gun-powder-light',

  TERMINAL_BG = 'terminal-bg',
  GREY_FONT = 'grey-font',
  BLACK_OPACITY = 'black-opacity',
  NAVIGATION_SLIDER = 'navigation-slider',
  PAGE_BACKGROUND = 'page-background',
  ACTIVE_TAB_PRIMARY = 'active-tab-primary',
  LIGHT_BLACK = 'light-black',
  LIGHT_RED = 'light-red',
  RED = 'red',
  RED_LIGHTER = 'red-lighter',
  DARK_PINK = 'dark-pink',
  LIGHT_BLUE = 'light-blue',
  LIGHT_PRIMARY = 'light-primary',
  ORANGE = 'orange',
  DARK_PURPLE = 'dark-purple',
  ORANGE_LIGHT = 'orange-light',
  YELLOW_LIGHT = 'yellow-light',
  DARK_YELLOW = 'dark-yellow',
  LIGHT_GREEN = 'light-green',
  BLUE_PRIMARY = 'blue-primary',
  BLUE_LIGHT_PRIMARY = 'blue-light-primary',
  ANALYTICS_TURQUOISE = 'analytics-turquoise',
  ANALYTICS_LIGHT_TURQUOISE = 'analytics-light-turquoise',
  ANALYTICS_LIGHT_ORANGE = 'analytics-light-orange',
  ANALYTICS_YELLOW = 'analytics-yellow',
  ANALYTICS_PINK = 'analytics-pink',
  ANALYTICS_LIGHT_BLUE = 'analytics-light-blue',
  ANALYTICS_BLUE = 'analytics-blue',
  RANK_GOLD_BG = 'rank-gold-bg',
  RANK_GOLD_BORDER = 'rank-gold-border',
  RANK_BRONZE_BG = 'rank-bronze-bg',
  RANK_BRONZE_BORDER = 'rank-bronze-border',
  RANK_SILVER_BG = 'rank-silver-bg',
  RANK_SILVER_BORDER = 'rank-silver-border',
  RANK_PLATINUM_BG = 'rank-platinum-bg',
  RANK_PLATINUM_BORDER = 'rank-platinum-border',
  RANK_OTHER_BG = 'rank-other-bg',
  RANK_OTHER_BORDER = 'rank-other-border',
  CONDITION_ITEM_BACKGROUND = 'condition-item-background',
  INSTAGRAM = 'instagram',
  TWITTER = 'twitter',
  YOUTUBE = 'youtube',
  FACEBOOK = 'facebook',
  BLOG = 'blog',
  EMAIL = 'email',
  PRIMARY_BLUE = 'primary-blue',
  LIGHT_GREY = 'light-grey',
  GREY_LIGHTER = 'grey-lighter',
  GREY = 'grey',
  DEAL_PAYMENT_TYPE = 'deal-payment-type',
  DRAFT_BUTTON = 'draft-button',
  DRAFT_BUTTON_BG = 'draft-button-bg',
  RECEIPT_ORANGE = 'receipt-orange',
  RECEIPT_BLUE = 'receipt-blue',
  PREVIEW_PRIMARY = 'preview-primary',
  PREVIEW_BG = 'preview-bg',
}
